# Generated by Django 4.1.3 on 2022-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_creation_date_post_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
